# Generated by Django 4.2.3 on 2023-08-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileUploadApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='name',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='original_name',
            field=models.CharField(default='No original name', max_length=255),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
