# Generated by Django 4.2.3 on 2023-08-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileUploadApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='uploaded_date',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='age',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='name',
            field=models.CharField(default='O', max_length=100),
        ),
    ]
