# Generated by Django 4.2.3 on 2023-08-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileUploadApp', '0002_remove_uploadedfile_uploaded_date_uploadedfile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='uploaded_date',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
